//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.05 at 04:38:39 PM UTC 
//

package it.unive.ros.sros2policies.jaxb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Policy_QNAME = new QName("", "policy");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Policy }
	 */
	public Policy createPolicy() {
		return new Policy();
	}

	/**
	 * Create an instance of {@link Enclaves }
	 */
	public Enclaves createEnclaves() {
		return new Enclaves();
	}

	/**
	 * Create an instance of {@link Enclave }
	 */
	public Enclave createEnclave() {
		return new Enclave();
	}

	/**
	 * Create an instance of {@link Profiles }
	 */
	public Profiles createProfiles() {
		return new Profiles();
	}

	/**
	 * Create an instance of {@link Profile }
	 */
	public Profile createProfile() {
		return new Profile();
	}

	/**
	 * Create an instance of {@link TopicExpressionList }
	 */
	public TopicExpressionList createTopicExpressionList() {
		return new TopicExpressionList();
	}

	/**
	 * Create an instance of {@link ServicesExpressionList }
	 */
	public ServicesExpressionList createServicesExpressionList() {
		return new ServicesExpressionList();
	}

	/**
	 * Create an instance of {@link ActionsExpressionList }
	 */
	public ActionsExpressionList createActionsExpressionList() {
		return new ActionsExpressionList();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Policy
	 * }{@code >}
	 * 
	 * @param value Java instance representing xml element's value.
	 * 
	 * @return the new instance of {@link JAXBElement }{@code <}{@link Policy
	 *             }{@code >}
	 */
	@XmlElementDecl(namespace = "", name = "policy")
	public JAXBElement<Policy> createPolicy(
			Policy value) {
		return new JAXBElement<Policy>(_Policy_QNAME, Policy.class, null, value);
	}

}
