//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.05 at 04:38:39 PM UTC 
//

package it.unive.ros.sros2policies.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for TopicExpressionList complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TopicExpressionList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded"&gt;
 *         &lt;element name="topic" type="{}Expression"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="publish" type="{}RuleQualifier" /&gt;
 *       &lt;attribute name="subscribe" type="{}RuleQualifier" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TopicExpressionList", propOrder = {
		"topic"
})
public class TopicExpressionList {

	@XmlElement(required = true)
	protected List<String> topic;
	@XmlAttribute(name = "publish")
	protected RuleQualifier publish;
	@XmlAttribute(name = "subscribe")
	protected RuleQualifier subscribe;

	/**
	 * Gets the value of the topic property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the topic property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTopic().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 */
	public List<String> getTopic() {
		if (topic == null) {
			topic = new ArrayList<String>();
		}
		return this.topic;
	}

	/**
	 * Gets the value of the publish property.
	 * 
	 * @return possible object is {@link RuleQualifier }
	 */
	public RuleQualifier getPublish() {
		return publish;
	}

	/**
	 * Sets the value of the publish property.
	 * 
	 * @param value allowed object is {@link RuleQualifier }
	 */
	public void setPublish(
			RuleQualifier value) {
		this.publish = value;
	}

	/**
	 * Gets the value of the subscribe property.
	 * 
	 * @return possible object is {@link RuleQualifier }
	 */
	public RuleQualifier getSubscribe() {
		return subscribe;
	}

	/**
	 * Sets the value of the subscribe property.
	 * 
	 * @param value allowed object is {@link RuleQualifier }
	 */
	public void setSubscribe(
			RuleQualifier value) {
		this.subscribe = value;
	}

}
