[INFO ] 2020-12-30 17:21:10.920 [main] PyToCFG - PyToCFG setup...
[INFO ] 2020-12-30 17:21:10.928 [main] PyToCFG - Reading file... src/test/resources/pyTest/py1.py
[INFO ] 2020-12-30 17:21:11.025 [main] PyToCFG - (file_input \r\n (stmt (compound_stmt (funcdef def _repr_info (parameters ( (typedargslist (tfpdef self)) )) : (suite             (stmt (compound_stmt (for_stmt for (exprlist (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom x))))))))))) in (testlist (test (or_test (and_test (not_test (comparison (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom fruits)))))))))))))))) : (suite                    (stmt (simple_stmt (small_stmt (expr_stmt (testlist_star_expr (test (or_test (and_test (not_test (comparison (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom print) (trailer ( (arglist (argument (test (or_test (and_test (not_test (comparison (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom x))))))))))))))))) ))))))))))))))))))) ))) ))))) ))))) nt(x))
[INFO ] 2020-12-30 17:21:11.028 [main] PyToCFG - Parsing stmt lists... [start]
[INFO ] 2020-12-30 17:21:11.031 [main] PyToCFG - Parsing stmt lists...: 1/1
[INFO ] 2020-12-30 17:21:52.564 [main] PyToCFG - PyToCFG setup...
[INFO ] 2020-12-30 17:21:52.567 [main] PyToCFG - Reading file... src/test/resources/pyTest/py1.py
[INFO ] 2020-12-30 17:21:52.647 [main] PyToCFG - (file_input \r\n (stmt (compound_stmt (funcdef def _repr_info (parameters ( (typedargslist (tfpdef self)) )) : (suite             (stmt (compound_stmt (for_stmt for (exprlist (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom x))))))))))) in (testlist (test (or_test (and_test (not_test (comparison (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom fruits)))))))))))))))) : (suite                    (stmt (simple_stmt (small_stmt (expr_stmt (testlist_star_expr (test (or_test (and_test (not_test (comparison (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom print) (trailer ( (arglist (argument (test (or_test (and_test (not_test (comparison (expr (xor_expr (and_expr (shift_expr (arith_expr (term (factor (power (atom_expr (atom x))))))))))))))))) ))))))))))))))))))) ))) ))))) ))))) nt(x))
[INFO ] 2020-12-30 17:21:52.650 [main] PyToCFG - Parsing stmt lists... [start]
[INFO ] 2020-12-30 17:21:52.659 [main] PyToCFG - Parsing stmt lists...: 1/1
[INFO ] 2020-12-30 17:21:52.663 [main] PyToCFG - NAME:
[INFO ] 2020-12-30 17:21:52.665 [main] PyToCFG - x
