//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.22 at 03:06:47 PM CEST 
//

package it.unive.ros.permissions.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Criteria complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Criteria"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="topics" type="{}TopicExpressionList"/&gt;
 *         &lt;element name="partitions" type="{}PartitionExpressionList" minOccurs="0"/&gt;
 *         &lt;element name="data_tags" type="{}DataTags" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Criteria", propOrder = {

})
public class Criteria {

	@XmlElement(required = true)
	protected TopicExpressionList topics;
	protected PartitionExpressionList partitions;
	@XmlElement(name = "data_tags")
	protected DataTags dataTags;

	/**
	 * Gets the value of the topics property.
	 * 
	 * @return possible object is {@link TopicExpressionList }
	 */
	public TopicExpressionList getTopics() {
		return topics;
	}

	/**
	 * Sets the value of the topics property.
	 * 
	 * @param value allowed object is {@link TopicExpressionList }
	 */
	public void setTopics(
			TopicExpressionList value) {
		this.topics = value;
	}

	/**
	 * Gets the value of the partitions property.
	 * 
	 * @return possible object is {@link PartitionExpressionList }
	 */
	public PartitionExpressionList getPartitions() {
		return partitions;
	}

	/**
	 * Sets the value of the partitions property.
	 * 
	 * @param value allowed object is {@link PartitionExpressionList }
	 */
	public void setPartitions(
			PartitionExpressionList value) {
		this.partitions = value;
	}

	/**
	 * Gets the value of the dataTags property.
	 * 
	 * @return possible object is {@link DataTags }
	 */
	public DataTags getDataTags() {
		return dataTags;
	}

	/**
	 * Sets the value of the dataTags property.
	 * 
	 * @param value allowed object is {@link DataTags }
	 */
	public void setDataTags(
			DataTags value) {
		this.dataTags = value;
	}

}
