//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.22 at 03:06:47 PM CEST 
//

package it.unive.ros.permissions.jaxb;

import jakarta.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for DomainIdSet complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="DomainIdSet"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="id" type="{}DomainId"/&gt;
 *         &lt;element name="id_range" type="{}DomainIdRange"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainIdSet", propOrder = {
		"idOrIdRange"
})
public class DomainIdSet {

	@XmlElements({
			@XmlElement(name = "id", type = BigInteger.class),
			@XmlElement(name = "id_range", type = DomainIdRange.class)
	})
	protected List<Object> idOrIdRange;

	/**
	 * Gets the value of the idOrIdRange property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the idOrIdRange property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getIdOrIdRange().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link BigInteger } {@link DomainIdRange }
	 */
	public List<Object> getIdOrIdRange() {
		if (idOrIdRange == null) {
			idOrIdRange = new ArrayList<Object>();
		}
		return this.idOrIdRange;
	}

}
