//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.22 at 03:06:47 PM CEST 
//


package it.unive.ros.permissions.jaxb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import java.math.BigInteger;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Dds_QNAME = new QName("", "dds");
    private final static QName _TagNameValuePairName_QNAME = new QName("", "name");
    private final static QName _TagNameValuePairValue_QNAME = new QName("", "value");
    private final static QName _DomainIdRangeMin_QNAME = new QName("", "min");
    private final static QName _DomainIdRangeMax_QNAME = new QName("", "max");
    private final static QName _GrantAllowRule_QNAME = new QName("", "allow_rule");
    private final static QName _GrantDenyRule_QNAME = new QName("", "deny_rule");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PermissionsNode }
     * 
     */
    public PermissionsNode createPermissionsNode() {
        return new PermissionsNode();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link Grant }
     * 
     */
    public Grant createGrant() {
        return new Grant();
    }

    /**
     * Create an instance of {@link Validity }
     * 
     */
    public Validity createValidity() {
        return new Validity();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link DomainIdSet }
     * 
     */
    public DomainIdSet createDomainIdSet() {
        return new DomainIdSet();
    }

    /**
     * Create an instance of {@link DomainIdRange }
     * 
     */
    public DomainIdRange createDomainIdRange() {
        return new DomainIdRange();
    }

    /**
     * Create an instance of {@link Criteria }
     * 
     */
    public Criteria createCriteria() {
        return new Criteria();
    }

    /**
     * Create an instance of {@link TopicExpressionList }
     * 
     */
    public TopicExpressionList createTopicExpressionList() {
        return new TopicExpressionList();
    }

    /**
     * Create an instance of {@link PartitionExpressionList }
     * 
     */
    public PartitionExpressionList createPartitionExpressionList() {
        return new PartitionExpressionList();
    }

    /**
     * Create an instance of {@link DataTags }
     * 
     */
    public DataTags createDataTags() {
        return new DataTags();
    }

    /**
     * Create an instance of {@link TagNameValuePair }
     * 
     */
    public TagNameValuePair createTagNameValuePair() {
        return new TagNameValuePair();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PermissionsNode }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PermissionsNode }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "dds")
    public JAXBElement<PermissionsNode> createDds(PermissionsNode value) {
        return new JAXBElement<PermissionsNode>(_Dds_QNAME, PermissionsNode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "name", scope = TagNameValuePair.class)
    public JAXBElement<String> createTagNameValuePairName(String value) {
        return new JAXBElement<String>(_TagNameValuePairName_QNAME, String.class, TagNameValuePair.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "value", scope = TagNameValuePair.class)
    public JAXBElement<String> createTagNameValuePairValue(String value) {
        return new JAXBElement<String>(_TagNameValuePairValue_QNAME, String.class, TagNameValuePair.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "min", scope = DomainIdRange.class)
    public JAXBElement<BigInteger> createDomainIdRangeMin(BigInteger value) {
        return new JAXBElement<BigInteger>(_DomainIdRangeMin_QNAME, BigInteger.class, DomainIdRange.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "max", scope = DomainIdRange.class)
    public JAXBElement<BigInteger> createDomainIdRangeMax(BigInteger value) {
        return new JAXBElement<BigInteger>(_DomainIdRangeMax_QNAME, BigInteger.class, DomainIdRange.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rule }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Rule }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "allow_rule", scope = Grant.class)
    public JAXBElement<Rule> createGrantAllowRule(Rule value) {
        return new JAXBElement<Rule>(_GrantAllowRule_QNAME, Rule.class, Grant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rule }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Rule }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "deny_rule", scope = Grant.class)
    public JAXBElement<Rule> createGrantDenyRule(Rule value) {
        return new JAXBElement<Rule>(_GrantDenyRule_QNAME, Rule.class, Grant.class, value);
    }

}
