//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.22 at 03:06:47 PM CEST 
//

package it.unive.ros.permissions.jaxb;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PermissionsNode complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="PermissionsNode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="permissions" type="{}Permissions"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PermissionsNode", propOrder = {
		"permissions"
})
public class PermissionsNode {

	@XmlElement(required = true)
	protected Permissions permissions;

	/**
	 * Gets the value of the permissions property.
	 * 
	 * @return possible object is {@link Permissions }
	 */
	public Permissions getPermissions() {
		return permissions;
	}

	/**
	 * Sets the value of the permissions property.
	 * 
	 * @param value allowed object is {@link Permissions }
	 */
	public void setPermissions(Permissions value) {
		this.permissions = value;
	}

}
